# Generated by Django 2.2.3 on 2019-08-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('sender', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('cc_myself', models.BooleanField(blank=True)),
                ('time', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
