# Generated by Django 2.2.3 on 2019-08-19 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
